let scene,camera,renderer,clock,player,playerModel,weapon,started=false,mixer,actions={},activeAction;let enemies=[],particles=[],hp=100,maxHp=100;let input={x:0,z:0},yaw=0,pitch=.28,attackCD=0;
const $=id=>document.getElementById(id);const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function mat(c,r=.5,m=.25,e=0){return new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m,emissive:e,emissiveIntensity:e?1.5:0})}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x05070c);scene.fog=new THREE.Fog(0x070910,18,70);camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,120);renderer=new THREE.WebGLRenderer({antialias:innerWidth>700,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1:1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;document.body.prepend(renderer.domElement);clock=new THREE.Clock();world();loadHero();resize();animate()}
function world(){let f=new THREE.Mesh(new THREE.PlaneGeometry(80,80),mat(0x11141b,.95));f.rotation.x=-Math.PI/2;f.receiveShadow=true;scene.add(f);for(let i=0;i<30;i++){let g=new THREE.BoxGeometry(2+Math.random()*2,1+Math.random()*3,2+Math.random()*2),o=new THREE.Mesh(g,mat(0x1b202a,.9,.15));o.position.set((Math.random()-.5)*60,(g.parameters.height/2), (Math.random()-.5)*60);o.castShadow=o.receiveShadow=true;scene.add(o)}let amb=new THREE.HemisphereLight(0x9aaaff,0x111111,1.2);scene.add(amb);let key=new THREE.DirectionalLight(0xffffff,2.2);key.position.set(8,14,6);key.castShadow=true;key.shadow.mapSize.set(1024,1024);scene.add(key);let rim=new THREE.PointLight(0x684cff,25,28);rim.position.set(0,5,-18);scene.add(rim);for(let i=0;i<6;i++){let l=new THREE.PointLight(0x573cff,10,12);l.position.set((i-2.5)*8,2,-12+Math.random()*18);scene.add(l)}}
function loadHero(){let loader=new THREE.GLTFLoader();loader.load('https://threejs.org/examples/models/gltf/Soldier.glb',g=>{player=g.scene;playerModel=g.scene;player.scale.setScalar(1.35);player.position.set(0,0,8);player.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});scene.add(player);mixer=new THREE.AnimationMixer(player);g.animations.forEach(a=>actions[a.name]=mixer.clipAction(a));activeAction=actions.Idle;activeAction.play();makeSword();spawnEnemies();},undefined,e=>{console.error(e);fallbackHero();})}
function fallbackHero(){player=new THREE.Group();let body=new THREE.Mesh(new THREE.CapsuleGeometry(.55,1.1,8,16),mat(0x24304d,.35,.45));body.position.y=1;let head=new THREE.Mesh(new THREE.SphereGeometry(.38,20,14),mat(0xd0b09b,.5));head.position.y=2;player.add(body,head);player.position.set(0,0,8);scene.add(player);makeSword();spawnEnemies()}
function makeSword(){weapon=new THREE.Group();let blade=new THREE.Mesh(new THREE.BoxGeometry(.12,1.8,.28),mat(0xdfeaff,.08,.95));blade.position.y=.55;blade.rotation.z=-.08;let guard=new THREE.Mesh(new THREE.BoxGeometry(.7,.1,.16),mat(0x8c63ff,.2,.8));guard.position.y=-.35;let grip=new THREE.Mesh(new THREE.CylinderGeometry(.07,.07,.55,10),mat(0x25202a,.6,.4));grip.position.y=-.67;weapon.add(blade,guard,grip);weapon.position.set(.72,1.25,.05);weapon.rotation.z=-.45;player.add(weapon)}
function enemy(){let g=new THREE.Group();let b=new THREE.Mesh(new THREE.CapsuleGeometry(.48,.9,6,10),mat(0x24132d,.45,.35,0x25002f));b.position.y=.95;let h=new THREE.Mesh(new THREE.SphereGeometry(.34,16,10),mat(0x180e20,.45,.35,0x4b0870));h.position.y=1.85;g.add(b,h);let eye=new THREE.PointLight(0xff2e78,2,4);eye.position.y=1.7;g.add(eye);g.userData.hp=50;g.userData.speed=.7;return g}
function spawnEnemies(){for(let i=0;i<8;i++){let e=enemy(),a=Math.random()*Math.PI*2,r=10+Math.random()*18;e.position.set(Math.cos(a)*r,0,Math.sin(a)*r);scene.add(e);enemies.push(e)}}
function attack(){if(!started||attackCD>0)return;attackCD=.35;if(weapon){weapon.rotation.x=-1.1;setTimeout(()=>weapon.rotation.x=0,150)}let target=enemies.filter(e=>e.position.distanceTo(player.position)<3.5).sort((a,b)=>a.position.distanceTo(player.position)-b.position.distanceTo(player.position))[0];if(target){target.userData.hp-=35;burst(target.position,0x9d5cff,14);if(target.userData.hp<=0){scene.remove(target);enemies=enemies.filter(x=>x!==target);if(!enemies.length){spawnEnemies();toast('DUNGEON CLEARED')}}}}
function burst(pos,c,n){for(let i=0;i<n;i++){let p=new THREE.Mesh(new THREE.SphereGeometry(.045,5,5),new THREE.MeshBasicMaterial({color:c}));p.position.copy(pos);p.userData={v:new THREE.Vector3((Math.random()-.5)*4,Math.random()*4,(Math.random()-.5)*4),life:.6};scene.add(p);particles.push(p)}}
function toast(t){let e=$('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),900)}
function move(dt){let v=new THREE.Vector3(input.x,0,input.z);if(v.length()>1)v.normalize();let moving=v.length()>.05;if(moving){let worldDir=new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw));let right=new THREE.Vector3(worldDir.z,0,-worldDir.x);let dir=right.multiplyScalar(v.x).add(worldDir.multiplyScalar(v.z)).normalize();player.position.addScaledVector(dir,5.5*dt);player.rotation.y=Math.atan2(dir.x,dir.z);if(actions.Run&&actions.Walk){let a=actions.Run;activeAction!==a&&(activeAction?.fadeOut(.15),a.reset().fadeIn(.15).play(),activeAction=a)}}else if(actions.Idle&&activeAction!==actions.Idle){activeAction?.fadeOut(.15);actions.Idle.reset().fadeIn(.15).play();activeAction=actions.Idle}player.position.x=clamp(player.position.x,-30,30);player.position.z=clamp(player.position.z,-30,30);if(mixer)mixer.update(dt)}
function update(dt){if(!player)return;attackCD=Math.max(0,attackCD-dt);move(dt);enemies.forEach(e=>{let d=e.position.distanceTo(player.position);if(d>1.6){let dir=player.position.clone().sub(e.position).normalize();e.position.addScaledVector(dir,e.userData.speed*dt);e.lookAt(player.position.x,e.position.y,player.position.z)}else hp=Math.max(0,hp-3*dt)});particles.forEach(p=>{p.position.addScaledVector(p.userData.v,dt);p.userData.v.y-=7*dt;p.userData.life-=dt;if(p.userData.life<=0){scene.remove(p);particles=particles.filter(x=>x!==p)}});let target=new THREE.Vector3(0,2,5.8).applyAxisAngle(new THREE.Vector3(0,1,0),yaw).add(player.position);camera.position.lerp(target,.12);camera.lookAt(player.position.x,1.25,player.position.z);$('hpText').textContent=`${Math.ceil(hp)} / ${maxHp}`;$('hpBar').style.width=`${hp/maxHp*100}%`}
function animate(){requestAnimationFrame(animate);let dt=Math.min(clock.getDelta(),.033);if(mixer&&!started)mixer.update(dt);update(dt);renderer.render(scene,camera)}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}
addEventListener('resize',resize);addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(k==='w')input.z=1;if(k==='s')input.z=-1;if(k==='a')input.x=-1;if(k==='d')input.x=1});addEventListener('keyup',e=>{let k=e.key.toLowerCase();if(k==='w'||k==='s')input.z=0;if(k==='a'||k==='d')input.x=0});addEventListener('mousedown',attack);addEventListener('mousemove',e=>{if(started&&document.pointerLockElement===renderer.domElement){yaw-=e.movementX*.003;pitch=clamp(pitch-e.movementY*.002,-.1,.8)}});$('start').onclick=()=>{started=true;$('menu').classList.add('hidden');$('hud').classList.remove('hidden');renderer.domElement.requestPointerLock?.();toast('AWAKENED')};$('restart').onclick=()=>location.reload();
function touch(){let j=document.createElement('div');j.id='touchMove';j.innerHTML='<div id="stick"><i></i></div><button id="atk">⚔</button>';document.body.appendChild(j);let s=document.querySelector('#stick'),k=s.querySelector('i'),on=false,cx=0,cy=0;s.onpointerdown=e=>{on=true;let r=s.getBoundingClientRect();cx=r.left+r.width/2;cy=r.top+r.height/2;s.setPointerCapture(e.pointerId)};s.onpointermove=e=>{if(!on)return;let dx=e.clientX-cx,dy=e.clientY-cy,m=38,d=Math.hypot(dx,dy);if(d>m){dx=dx/d*m;dy=dy/d*m}k.style.transform=`translate(${dx}px,${dy}px)`;input.x=dx/m;input.z=-dy/m};s.onpointerup=()=>{on=false;k.style.transform='';input.x=input.z=0};document.querySelector('#atk').onpointerdown=attack}touch();init();