let scene,camera,renderer,clock,player,weapon,started=false,locked=false;let hp=100,maxHp=100,xp=0,level=1,floor=1,kills=0;let enemies=[],particles=[],keys={};let attackReady=true,skillReady={slash:true,burst:true,dash:true};
const $=id=>document.getElementById(id); const toast=m=>{let t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),1400)};
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x03040a);scene.fog=new THREE.FogExp2(0x080914,.045);camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.1,300);camera.position.set(0,2.2,7);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.body.prepend(renderer.domElement);clock=new THREE.Clock();
 const hemi=new THREE.HemisphereLight(0x8888bb,0x090910,1.1);scene.add(hemi);const moon=new THREE.DirectionalLight(0x9d9aff,2.5);moon.position.set(8,14,5);moon.castShadow=true;moon.shadow.mapSize.set(2048,2048);scene.add(moon);buildDungeon();createPlayer();spawnWave();resize();animate();}
function mat(c,rough=.7,metal=0){return new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:metal})}
function box(x,y,z,c){let m=new THREE.Mesh(new THREE.BoxGeometry(x,y,z),mat(c));m.castShadow=true;m.receiveShadow=true;return m}
function buildDungeon(){let floorMat=mat(0x10131d,.95);let floor=new THREE.Mesh(new THREE.PlaneGeometry(110,110),floorMat);floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);for(let x=-25;x<=25;x+=5)for(let z=-25;z<=25;z+=5){let tile=box(4.7,.08,4.7,(x+z)%10?0x111522:0x15182a);tile.position.set(x,-.01,z);scene.add(tile)}
 const walls=[[0,-30,60,5],[0,30,60,5],[-30,0,5,60],[30,0,5,60],[-10,-10,3,24],[10,10,3,24],[-15,15,20,3],[15,-15,20,3]];walls.forEach(([x,z,w,d])=>{let m=box(w,6,d,0x171a29);m.position.set(x,3,z);scene.add(m);});
 for(let i=0;i<22;i++){let x=(Math.random()-.5)*48,z=(Math.random()-.5)*48; if(Math.abs(x)<7&&Math.abs(z)<7)continue;let p=box(.35,Math.random()*2+.7,.35,0x242842);p.position.set(x,p.geometry.parameters.height/2,z);scene.add(p)}
 for(let i=0;i<8;i++){let l=new THREE.PointLight(i%2?0x6d4dff:0x3e8dff,3,12);l.position.set((Math.random()-.5)*42,2.5,(Math.random()-.5)*42);scene.add(l)} }
function createPlayer(){player=new THREE.Group();let body=new THREE.Mesh(new THREE.CapsuleGeometry(.48,.9,6,12),mat(0x15182b,.45,.5));body.position.y=1.1;body.castShadow=true;player.add(body);let head=new THREE.Mesh(new THREE.SphereGeometry(.38,16,16),mat(0xb9bfd8,.5));head.position.y=1.95;head.castShadow=true;player.add(head);let glow=new THREE.PointLight(0x6555ff,2,7);glow.position.y=1.2;player.add(glow);weapon=new THREE.Mesh(new THREE.BoxGeometry(.12,1.5,.28),mat(0xa9b5ff,.2,.8));weapon.position.set(.7,1.1,0);weapon.rotation.z=-.35;weapon.castShadow=true;player.add(weapon);player.position.set(0,0,8);scene.add(player)}
function spawnEnemy(type='shadow'){let e=new THREE.Group();let c=type==='elite'?0x63295f:0x211b38;let body=new THREE.Mesh(new THREE.CapsuleGeometry(.5,.9,5,10),mat(c,.65,.25));body.position.y=1;body.castShadow=true;e.add(body);let eye=new THREE.PointLight(type==='elite'?0xff4f8a:0x7d59ff,3,5);eye.position.y=1.4;e.add(eye);let a=Math.random()*Math.PI*2,r=11+Math.random()*13;e.position.set(Math.cos(a)*r,0,Math.sin(a)*r);e.userData={hp:type==='elite'?65:30,max:type==='elite'?65:30,speed:type==='elite'?1.25:.8,elite:type==='elite',hit:0};scene.add(e);enemies.push(e)}
function spawnWave(){let n=5+floor*2;for(let i=0;i<n;i++)spawnEnemy(i===n-1?'elite':'shadow');$('objective').textContent=`Defeat ${n} shadows`;}
function damageEnemy(e,d){e.userData.hp-=d;e.scale.setScalar(1.08);setTimeout(()=>e.scale.setScalar(1),70);burst(e.position,0x8e70ff,7);if(e.userData.hp<=0){scene.remove(e);enemies=enemies.filter(x=>x!==e);kills++;gainXP(e.userData.elite?45:20);if(enemies.length===0){floor++;$('floor').textContent=String(floor).padStart(2,'0');toast('DUNGEON CLEARED • NEXT FLOOR');setTimeout(spawnWave,900)}}}
function gainXP(v){xp+=v;while(xp>=100){xp-=100;level++;maxHp+=15;hp=maxHp;toast('LEVEL UP • SHADOW AWAKENED');}updateHud()}
function playerAttack(){if(!attackReady||!started)return;attackReady=false;weapon.rotation.x=-.9;setTimeout(()=>weapon.rotation.x=0,120);let nearest=enemies.filter(e=>e.position.distanceTo(player.position)<3.3).sort((a,b)=>a.position.distanceTo(player.position)-b.position.distanceTo(player.position))[0];if(nearest)damageEnemy(nearest,25+level*4);setTimeout(()=>attackReady=true,260)}
function skill(name){if(!skillReady[name]||!started)return;skillReady[name]=false;if(name==='slash'){enemies.filter(e=>e.position.distanceTo(player.position)<4).forEach(e=>damageEnemy(e,45+level*7));toast('SHADOW SLASH')}if(name==='burst'){enemies.filter(e=>e.position.distanceTo(player.position)<7).forEach(e=>damageEnemy(e,25+level*4));burst(player.position,0x8d5cff,45);toast('SHADOW BURST')}if(name==='dash'){let dir=new THREE.Vector3(Math.sin(player.rotation.y),0,Math.cos(player.rotation.y));player.position.addScaledVector(dir,-5);burst(player.position,0x6b5bff,18);toast('SHADOW STEP')}setTimeout(()=>skillReady[name]=true,1800)}
function burst(pos,color,count){for(let i=0;i<count;i++){let p=new THREE.Mesh(new THREE.SphereGeometry(.045,5,5),new THREE.MeshBasicMaterial({color,transparent:true}));p.position.copy(pos);p.userData.v=new THREE.Vector3((Math.random()-.5)*4,Math.random()*3,(Math.random()-.5)*4);p.userData.life=.7;scene.add(p);particles.push(p)}}
function updateHud(){$('level').textContent=`LV ${level}`;$('hpText').textContent=`${Math.ceil(hp)} / ${maxHp}`;$('hpBar').style.width=`${Math.max(0,hp/maxHp)*100}%`;$('xpText').textContent=`${xp} / 100`;$('xpBar').style.width=`${xp}%`}
function update(dt){if(!started)return;let speed=5.5*dt;let f=(keys.w?1:0)-(keys.s?1:0),r=(keys.d?1:0)-(keys.a?1:0);let v=new THREE.Vector3(r,0,f);if(v.length())v.normalize();player.position.x+=v.x*speed;player.position.z+=v.z*speed;player.position.x=THREE.MathUtils.clamp(player.position.x,-26,26);player.position.z=THREE.MathUtils.clamp(player.position.z,-26,26);camera.position.lerp(new THREE.Vector3(player.position.x,3.2,player.position.z+6),.12);camera.lookAt(player.position.x,1.3,player.position.z);enemies.forEach(e=>{let d=e.position.distanceTo(player.position);if(d>1.25){let dir=player.position.clone().sub(e.position).normalize();e.position.addScaledVector(dir,e.userData.speed*dt);e.lookAt(player.position.x,e.position.y,player.position.z)}else if(e.userData.hit<=0){hp-=e.userData.elite?9:4;e.userData.hit=1;updateHud();if(hp<=0)endGame(false)}});enemies.forEach(e=>e.userData.hit=Math.max(0,e.userData.hit-dt));particles.forEach(p=>{p.position.addScaledVector(p.userData.v,dt);p.userData.v.y-=4*dt;p.userData.life-=dt;p.scale.multiplyScalar(.97);if(p.userData.life<=0){scene.remove(p);particles=particles.filter(x=>x!==p)}})}
function animate(){requestAnimationFrame(animate);let dt=Math.min(clock.getDelta(),.05);update(dt);renderer.render(scene,camera)}
function startGame(){if(started)return;started=true;$('menu').classList.add('hidden');$('hud').classList.remove('hidden');$('centerPrompt').textContent='CLICK TO ATTACK';renderer.domElement.requestPointerLock?.();toast('DUNGEON 01 • BEGIN');}
function endGame(win){started=false;document.exitPointerLock?.();$('gameover').classList.remove('hidden');$('resultTitle').textContent=win?'DUNGEON CONQUERED':'THE SHADOWS PREVAILED';$('resultText').textContent=`Level ${level} · Floor ${floor} · ${kills} shadows defeated.`}
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='q')skill('slash');if(e.key.toLowerCase()==='e')skill('burst');if(e.key.toLowerCase()==='r')skill('dash')});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);addEventListener('mousedown',()=>{if(started)playerAttack()});document.querySelectorAll('.skills button').forEach(b=>b.addEventListener('click',()=>skill(b.dataset.skill)));$('start').onclick=startGame;$('restart').onclick=()=>location.reload();document.addEventListener('mousemove',e=>{if(!started||document.pointerLockElement!==renderer.domElement)return;player.rotation.y-=e.movementX*.002;});function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}addEventListener('resize',resize);setTimeout(()=>{$('boot').style.display='none';$('menu').classList.remove('hidden')},900);init();
