(() => {
let S,C,R,clock,hero,sword,enemies=[],particles=[],started=false,hp=100,move={x:0,z:0},attackCD=0;
const $=id=>document.getElementById(id); const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const mat=(color,rough=.7,metal=.1,emissive=0)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal,emissive,emissiveIntensity:emissive?2:0});
const mesh=(g,m)=>{const o=new THREE.Mesh(g,m);o.castShadow=o.receiveShadow=true;return o};
async function getFace(){try{const t=await fetch('game-v6.js').then(r=>r.text());const m=t.match(/const FACE='([^']+)'/);return m?m[1]:''}catch(e){return ''}}
function init(){S=new THREE.Scene();S.background=new THREE.Color(0x05070c);S.fog=new THREE.Fog(0x080a12,18,58);C=new THREE.PerspectiveCamera(56,innerWidth/innerHeight,.1,120);R=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});R.setSize(innerWidth,innerHeight);R.setPixelRatio(Math.min(devicePixelRatio,1.35));R.shadowMap.enabled=true;R.shadowMap.type=THREE.PCFSoftShadowMap;R.outputColorSpace=THREE.SRGBColorSpace;R.toneMapping=THREE.ACESFilmicToneMapping;document.body.prepend(R.domElement);clock=new THREE.Clock();buildDungeon();buildHero();spawnEnemies();buildControls();resize();requestAnimationFrame(loop)}
function buildDungeon(){const floor=mesh(new THREE.PlaneGeometry(90,90),mat(0x11141d,.92));floor.rotation.x=-Math.PI/2;S.add(floor);for(let x=-32;x<=32;x+=4)for(let z=-32;z<=32;z+=4)if(Math.random()<.38){const tile=mesh(new THREE.BoxGeometry(3.7,.08,3.7),mat(0x20242f,.85));tile.position.set(x,.02,z);S.add(tile)}for(const side of[-1,1]){const wall=mesh(new THREE.BoxGeometry(2,8,72),mat(0x24232b,.82));wall.position.set(side*30,4,0);S.add(wall);for(let z=-30;z<=30;z+=10){const col=mesh(new THREE.CylinderGeometry(1.25,1.45,8,8),mat(0x30303a,.68,.15));col.position.set(side*26,4,z);S.add(col)}}for(let z=-30;z<=30;z+=10){const arch=mesh(new THREE.BoxGeometry(58,1.5,1.2),mat(0x292a33,.78));arch.position.set(0,7.3,z);S.add(arch)}const gate=mesh(new THREE.BoxGeometry(16,10,.8),mat(0x181a22,.7,.2));gate.position.set(0,5,-30);S.add(gate);for(let x=-7;x<=7;x+=2){const bar=mesh(new THREE.BoxGeometry(.35,8,.55),mat(0x090b11,.35,.7));bar.position.set(x,4,-29.3);S.add(bar)}for(const x of[-20,-10,0,10,20]){torch(x,-27);torch(x,25)}S.add(new THREE.HemisphereLight(0x8c9cff,0x09070a,1.4));const key=new THREE.DirectionalLight(0xcbd4ff,1.8);key.position.set(-12,18,18);key.castShadow=true;key.shadow.mapSize.set(1024,1024);S.add(key)}
function torch(x,z){const pole=mesh(new THREE.CylinderGeometry(.08,.1,2.2,8),mat(0x21150f,.6,.3));pole.position.set(x,1.5,z);S.add(pole);const flame=mesh(new THREE.SphereGeometry(.22,10,8),new THREE.MeshBasicMaterial({color:0xff8b35}));flame.position.set(x,2.7,z);S.add(flame);const light=new THREE.PointLight(0xff7133,8,10);light.position.set(x,2.6,z);S.add(light)}
function buildHero(){hero=new THREE.Group();hero.position.set(0,0,14);const skin=mat(0xc68b74,.5),cloth=mat(0x090c15,.48,.45),coat=mat(0x151b2c,.45,.35),metal=mat(0xd5d9e8,.18,.9,0x5b4cff);for(const x of[-.28,.28]){const leg=mesh(new THREE.CapsuleGeometry(.15,.85,8,10),cloth);leg.position.set(x,.62,0);hero.add(leg)}const body=mesh(new THREE.CapsuleGeometry(.52,.9,10,14),coat);body.scale.set(1.05,1.15,.72);body.position.y=1.5;hero.add(body);const hood=mesh(new THREE.ConeGeometry(.6,.45,16),cloth);hood.rotation.x=Math.PI;hood.position.set(0,2.35,.02);hero.add(hood);const head=mesh(new THREE.SphereGeometry(.38,24,18),skin);head.position.y=2.32;hero.add(head);const hair=mesh(new THREE.SphereGeometry(.4,24,16,0,Math.PI*2,0,Math.PI*.55),mat(0x050609,.35,.25));hair.position.y=2.46;hero.add(hair);const cape=mesh(new THREE.BoxGeometry(1.15,1.7,.12),mat(0x05070d,.75,.25));cape.position.set(0,1.45,.45);hero.add(cape);sword=new THREE.Group();const blade=mesh(new THREE.BoxGeometry(.16,2.45,.32),metal);blade.position.y=.65;const edge=mesh(new THREE.BoxGeometry(.055,2.35,.06),new THREE.MeshBasicMaterial({color:0xa78bff}));edge.position.set(.09,.65,.17);const guard=mesh(new THREE.BoxGeometry(.9,.12,.2),mat(0x7f4dff,.2,.8,0x6d42ff));guard.position.y=-.55;const grip=mesh(new THREE.CylinderGeometry(.075,.075,.65,10),mat(0x171018,.35,.65));grip.position.y=-.92;sword.add(blade,edge,guard,grip);sword.position.set(.78,1.25,-.12);sword.rotation.z=-.55;hero.add(sword);S.add(hero);getFace().then(src=>{if(!src)return;const tex=new THREE.TextureLoader().load(src);const plane=new THREE.Mesh(new THREE.PlaneGeometry(.52,.65),new THREE.MeshBasicMaterial({map:tex,transparent:true}));plane.position.set(0,2.30,-.36);plane.rotation.y=Math.PI;hero.add(plane);const av=$('avatarFace');if(av){av.src=src;av.classList.add('ready')}})}
function enemy(){const g=new THREE.Group();const armor=mat(0x15111e,.38,.55,0x310b45),dark=mat(0x07080d,.45,.35),purple=new THREE.MeshBasicMaterial({color:0x8d42ff});const body=mesh(new THREE.CapsuleGeometry(.48,.95,8,12),armor);body.position.y=1.05;g.add(body);const head=mesh(new THREE.SphereGeometry(.33,18,12),dark);head.position.y=1.85;g.add(head);const blade=mesh(new THREE.BoxGeometry(.1,1.6,.18),purple);blade.position.set(.55,.95,0);blade.rotation.z=-.5;g.add(blade);const aura=new THREE.PointLight(0x8d32ff,4,5);aura.position.y=1.5;g.add(aura);g.userData={hp:100,speed:.75};return g}
function spawnEnemies(){enemies=[];[[-8,2],[0,-2],[9,0],[-13,-7],[13,-8],[-6,-14],[7,-17],[0,-23]].forEach(([x,z])=>{const e=enemy();e.position.set(x,0,z);S.add(e);enemies.push(e)})}
function attack(){if(!started||attackCD>0)return;attackCD=.32;sword.rotation.x=-1.2;setTimeout(()=>sword.rotation.x=0,140);const target=enemies.filter(e=>e.position.distanceTo(hero.position)<4.5).sort((a,b)=>a.position.distanceTo(hero.position)-b.position.distanceTo(hero.position))[0];if(target){target.userData.hp-=50;burst(target.position);if(target.userData.hp<=0){S.remove(target);enemies=enemies.filter(e=>e!==target);const q=$('questCount');if(q)q.textContent=(8-enemies.length)+' / 8'}}}
function burst(pos){for(let i=0;i<18;i++){const q=mesh(new THREE.SphereGeometry(.055,6,6),new THREE.MeshBasicMaterial({color:0xb36cff}));q.position.copy(pos);q.userData={v:new THREE.Vector3((Math.random()-.5)*5,Math.random()*4,(Math.random()-.5)*5),life:.65};S.add(q);particles.push(q)}}
function update(dt){if(!started)return;attackCD=Math.max(0,attackCD-dt);const v=new THREE.Vector3(move.x,0,move.z);if(v.length()>1)v.normalize();if(v.length()>.05){hero.position.x+=v.x*5*dt;hero.position.z+=v.z*5*dt;hero.rotation.y=Math.atan2(v.x,v.z)}hero.position.x=clamp(hero.position.x,-24,24);hero.position.z=clamp(hero.position.z,-26,24);enemies.forEach(e=>{const d=e.position.distanceTo(hero.position);if(d>2.2){e.position.add(hero.position.clone().sub(e.position).normalize().multiplyScalar(e.userData.speed*dt));e.lookAt(hero.position.x,1,hero.position.z)}else hp=Math.max(0,hp-6*dt)});particles.forEach(q=>{q.position.addScaledVector(q.userData.v,dt);q.userData.v.y-=7*dt;q.userData.life-=dt;if(q.userData.life<=0){S.remove(q);particles=particles.filter(x=>x!==q)}});C.position.lerp(new THREE.Vector3(hero.position.x,4.4,hero.position.z+8.6),.1);C.lookAt(hero.position.x,1.45,hero.position.z-2);$('hpText').textContent=Math.ceil(hp)+' / 100';$('hpBar').style.width=hp+'%'}
function buildControls(){const wrap=document.createElement('div');wrap.id='touchUI';wrap.innerHTML='<div id="joy"><i></i></div><button class="touch-attack" id="attackBtn">⚔</button>';document.body.appendChild(wrap);const j=$('joy'),k=j.querySelector('i');let on=false,cx=0,cy=0;j.onpointerdown=e=>{on=true;cx=e.clientX;cy=e.clientY;j.setPointerCapture(e.pointerId)};j.onpointermove=e=>{if(!on)return;let x=e.clientX-cx,y=e.clientY-cy,m=40,d=Math.hypot(x,y);if(d>m){x=x/d*m;y=y/d*m}k.style.transform=`translate(${x}px,${y}px)`;move.x=x/m;move.z=-y/m};j.onpointerup=j.onpointercancel=()=>{on=false;k.style.transform='';move.x=move.z=0};$('attackBtn').onpointerdown=attack;addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='w')move.z=-1;if(k==='s')move.z=1;if(k==='a')move.x=-1;if(k==='d')move.x=1;if(k===' '||k==='enter')attack()});addEventListener('keyup',e=>{const k=e.key.toLowerCase();if(k==='w'||k==='s')move.z=0;if(k==='a'||k==='d')move.x=0});addEventListener('mousedown',e=>{if(e.target===R.domElement)attack()});$('start').onclick=()=>{started=true;$('menu').classList.add('hidden');$('hud').classList.remove('hidden')}}
function resize(){C.aspect=innerWidth/innerHeight;C.updateProjectionMatrix();R.setSize(innerWidth,innerHeight)}function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.033);update(dt);R.render(S,C)}addEventListener('resize',resize);init();
})();