let scene,camera,renderer,clock,player,weapon,started=false;let hp=140,maxHp=140,xp=0,level=1,floor=1,kills=0,gold=0;let enemies=[],particles=[],pickups=[];let input={x:0,z:0};let attackCD=0,skillCD={slash:0,burst:0,dash:0},boss=null,shake=0;
const $=id=>document.getElementById(id);const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function material(c,r=.65,m=.15,e=0){return new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m,emissive:e,emissiveIntensity:e?1.2:0})}
function mesh(g,m){const o=new THREE.Mesh(g,m);o.castShadow=true;o.receiveShadow=true;return o}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x03040b);scene.fog=new THREE.FogExp2(0x080914,.028);camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,180);renderer=new THREE.WebGLRenderer({antialias:innerWidth>700,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.15:1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;document.body.prepend(renderer.domElement);clock=new THREE.Clock();setupWorld();makePlayer();spawnFloor();resize();animate()}
function setupWorld(){const floor=mesh(new THREE.PlaneGeometry(90,90),material(0x0a0d17,.95));floor.rotation.x=-Math.PI/2;scene.add(floor);for(let x=-24;x<=24;x+=4)for(let z=-24;z<=24;z+=4){let t=mesh(new THREE.BoxGeometry(3.85,.08,3.85),material((x+z)%8?0x111625:0x18172a,.9));t.position.set(x,-.03,z);scene.add(t)}const walls=[[0,-29,58,2],[0,29,58,2],[-29,0,2,58],[29,0,2,58],[-10,-5,2.2,15],[10,6,2.2,15],[-15,14,17,2.2],[15,-14,17,2.2]];walls.forEach(([x,z,w,d])=>{let b=mesh(new THREE.BoxGeometry(w,5,d),material(0x161a29,.8,.2));b.position.set(x,2.5,z);scene.add(b)});for(let i=0;i<18;i++){let p=mesh(new THREE.CylinderGeometry(.12,.25,.5+Math.random()*1.8,6),material(0x252a3e,.8,.2));p.position.set((Math.random()-.5)*48,.5,(Math.random()-.5)*48);scene.add(p)}for(let i=0;i<10;i++){let l=new THREE.PointLight(i%2?0x6e4dff:0x2d83ff,2.2,11);l.position.set((Math.random()-.5)*44,2,(Math.random()-.5)*44);scene.add(l)}let gate=mesh(new THREE.TorusGeometry(3.4,.28,8,32),material(0x704fff,.2,.8,0x3510aa));gate.rotation.x=Math.PI/2;gate.position.set(0,3,-25);scene.add(gate)}
function makePlayer(){player=new THREE.Group();let cloak=mesh(new THREE.ConeGeometry(.82,1.75,7,1,true),material(0x080a13,.52,.3));cloak.position.y=.82;cloak.rotation.x=Math.PI;player.add(cloak);let torso=mesh(new THREE.CapsuleGeometry(.45,.7,5,10),material(0x1c2340,.38,.45));torso.position.y=1.2;player.add(torso);let head=mesh(new THREE.SphereGeometry(.37,16,12),material(0xd1d6e8,.42));head.position.y=2;player.add(head);let hood=mesh(new THREE.ConeGeometry(.5,.55,6),material(0x090b14,.5,.3));hood.position.y=2.25;player.add(hood);let eye=new THREE.PointLight(0x7660ff,2.4,6);eye.position.y=1.65;player.add(eye);weapon=new THREE.Group();let blade=mesh(new THREE.BoxGeometry(.11,1.65,.22),material(0xcdd7ff,.12,.95));blade.position.y=.3;weapon.add(blade);let guard=mesh(new THREE.BoxGeometry(.58,.09,.18),material(0x8b66ff,.22,.8,0x2d0fff));guard.position.y=-.5;weapon.add(guard);weapon.position.set(.68,1.15,0);weapon.rotation.z=-.35;player.add(weapon);player.position.set(0,0,9);scene.add(player)}
function enemyModel(type){let e=new THREE.Group(),champ=type==='champion',elite=type==='elite',bossType=type==='boss';let col=bossType?0x38102e:champ?0x3b1f32:elite?0x2c1640:0x15172b;let body=mesh(new THREE.CapsuleGeometry(bossType?1.15:champ?.65:elite?.55:.45,bossType?1.7:champ?1.1:.85,6,10),material(col,.5,.35));body.position.y=bossType?1.75:champ?1.2:1;e.add(body);let core=mesh(new THREE.IcosahedronGeometry(bossType?.42:.2,1),material(bossType?0xff356f:elite?0xff5ca8:0x765cff,.2,.55,bossType?0xff174e:0x4b22ff));core.position.y=bossType?2.6:1.45;e.add(core);let horns=new THREE.Group();for(let s of [-1,1]){let h=mesh(new THREE.ConeGeometry(bossType?.25:.12,bossType?.9:.45,5),material(bossType?0x8e2c6e:0x38265e,.5,.2));h.position.set(s*(bossType?.65:.32),bossType?3.1:1.85,0);h.rotation.z=s*.45;horns.add(h)}e.add(horns);let glow=new THREE.PointLight(bossType?0xff3d82:elite?0xff3eaa:0x725cff,bossType?5:2.2,bossType?10:5);glow.position.y=bossType?2:1.3;e.add(glow);return e}
function spawnEnemy(type='shadow'){let e=enemyModel(type),bossType=type==='boss',champ=type==='champion',elite=type==='elite';let a=Math.random()*Math.PI*2,r=bossType?15:12+Math.random()*13;e.position.set(Math.cos(a)*r,0,Math.sin(a)*r);let base=bossType?520+floor*80:champ?150:elite?75:38;e.userData={hp:base,max:base,speed:bossType?.8:champ?.95:elite?1.2:.72,type,hit:0,attack:0};scene.add(e);enemies.push(e);if(bossType){boss=e;$('bossCard').classList.remove('hidden');$('bossName').textContent=`DREAD LORD · FLOOR ${String(floor).padStart(2,'0')}`}}
function spawnFloor(){enemies.forEach(e=>scene.remove(e));enemies=[];pickups.forEach(p=>scene.remove(p));pickups=[];boss=null;$('bossCard').classList.add('hidden');let n=Math.min(12,4+floor*2);for(let i=0;i<n;i++)spawnEnemy(i===n-1?'elite':'shadow');if(floor%3===0)setTimeout(()=>spawnEnemy('boss'),500);else if(floor>=2)spawnEnemy('champion');$('floor').textContent=String(floor).padStart(2,'0');$('objective').textContent=floor%3===0?'Defeat the Dread Lord':`Clear ${n} shadows`}
function particle(pos,c,n=10){for(let i=0;i<n;i++){let p=new THREE.Mesh(new THREE.SphereGeometry(.04,5,5),new THREE.MeshBasicMaterial({color:c,transparent:true}));p.position.copy(pos);p.userData={v:new THREE.Vector3((Math.random()-.5)*5,Math.random()*4,(Math.random()-.5)*5),life:.55};scene.add(p);particles.push(p)}}
function hitEnemy(e,dmg){e.userData.hp-=dmg;e.scale.setScalar(1.1);setTimeout(()=>e.parent&&(e.scale.setScalar(1)),60);particle(e.position,0x9677ff,e.userData.type==='boss'?18:8);shake=Math.min(.18,shake+.035);if(e.userData.hp<=0)killEnemy(e);updateHud();if(boss===e)$('bossBar').style.width='0%'}
function killEnemy(e){let wasBoss=e.userData.type==='boss';scene.remove(e);enemies=enemies.filter(x=>x!==e);kills++;gold+=wasBoss?300:e.userData.type==='champion'?70:e.userData.type==='elite'?40:12;gainXP(wasBoss?220:e.userData.type==='champion'?75:e.userData.type==='elite'?45:22);if(Math.random()<.28||wasBoss)drop(e.position,wasBoss);if(wasBoss||enemies.length===0){floor++;toast(wasBoss?'DREAD LORD SLAIN':'DUNGEON CLEARED');setTimeout(spawnFloor,900)}else toast(`+${gold?e.userData.type==='boss'?300:12:12} GOLD`)}
function drop(pos,relic){let p=mesh(new THREE.IcosahedronGeometry(.28,1),material(relic?0xffb13b:0x4e8dff,.2,.7,relic?0xff7a00:0x174cff));p.position.copy(pos);p.position.y=.5;p.userData={relic};scene.add(p);pickups.push(p)}
function gainXP(v){xp+=v;while(xp>=100){xp-=100;level++;maxHp+=22;hp=maxHp;toast(`LEVEL UP · LV ${level}`)}updateHud()}
function playerAttack(){if(!started||attackCD>0)return;attackCD=.24;weapon.rotation.x=-1.15;setTimeout(()=>weapon.rotation.x=0,120);let target=enemies.filter(e=>e.position.distanceTo(player.position)<3.8).sort((a,b)=>a.position.distanceTo(player.position)-b.position.distanceTo(player.position))[0];if(target){let dmg=30+level*6;hitEnemy(target,dmg);toast(`SHADOW STRIKE · ${dmg}`)}else particle(player.position,0x755fff,5)}
function skill(name){if(!started||skillCD[name]>0)return;skillCD[name]=name==='dash'?1.2:1.7;if(name==='slash'){enemies.filter(e=>e.position.distanceTo(player.position)<4.8).forEach(e=>hitEnemy(e,65+level*9));particle(player.position,0x9b6cff,35);toast('SHADOW SLASH')}if(name==='burst'){enemies.filter(e=>e.position.distanceTo(player.position)<8).forEach(e=>hitEnemy(e,42+level*7));particle(player.position,0x6f4cff,70);toast('SHADOW BURST')}if(name==='dash'){let d=new THREE.Vector3(input.x,0,input.z);if(d.length()<.2)d.set(0,0,-1);player.position.addScaledVector(d.normalize(),7);particle(player.position,0x6f5cff,25);toast('SHADOW STEP')}}
function update(dt){if(!started)return;attackCD=Math.max(0,attackCD-dt);Object.keys(skillCD).forEach(k=>skillCD[k]=Math.max(0,skillCD[k]-dt));let v=new THREE.Vector3(input.x,0,input.z);if(v.length()>1)v.normalize();player.position.addScaledVector(v,6.5*dt);player.position.x=clamp(player.position.x,-26,26);player.position.z=clamp(player.position.z,-26,26);if(v.length()>.05)player.rotation.y=Math.atan2(v.x,v.z);enemies.forEach(e=>{let d=e.position.distanceTo(player.position);e.userData.hit=Math.max(0,e.userData.hit-dt);if(d>1.65){let dir=player.position.clone().sub(e.position).normalize();e.position.addScaledVector(dir,e.userData.speed*dt);e.lookAt(player.position.x,e.position.y,player.position.z)}else if(e.userData.hit<=0){e.userData.hit=.9;let dmg=e.userData.type==='boss'?13:e.userData.type==='champion'?8:e.userData.type==='elite'?6:4;hp-=dmg;particle(player.position,0xff456f,4);updateHud();if(hp<=0)endGame()}});if(boss){$('bossBar').style.width=`${clamp(boss.userData.hp/boss.userData.max,0,1)*100}%`}pickups.forEach(p=>{p.rotation.y+=dt*2;p.position.y=.45+Math.sin(clock.elapsedTime*3+p.id)*.12;if(p.position.distanceTo(player.position)<1.4){if(p.userData.relic){maxHp+=10;hp=Math.min(maxHp,hp+55);toast('ANCIENT RELIC · MAX HP +10')}else{hp=Math.min(maxHp,hp+40);toast('HEALTH RESTORED +40')}scene.remove(p);pickups=pickups.filter(x=>x!==p);updateHud()}});particles.forEach(p=>{p.position.addScaledVector(p.userData.v,dt);p.userData.v.y-=5*dt;p.userData.life-=dt;p.scale.multiplyScalar(.95);if(p.userData.life<=0){scene.remove(p);particles=particles.filter(x=>x!==p)}});let cam=new THREE.Vector3(player.position.x,4.4,player.position.z+7.5);camera.position.lerp(cam,.09);camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake;camera.lookAt(player.position.x,1.2,player.position.z);shake=Math.max(0,shake-dt)}
function updateHud(){$('level').textContent=`LV ${level}`;$('hpText').textContent=`${Math.ceil(Math.max(0,hp))} / ${maxHp}`;$('hpBar').style.width=`${clamp(hp/maxHp,0,1)*100}%`;$('xpText').textContent=`${xp} / 100`;$('xpBar').style.width=`${xp}%`}
function toast(t){let el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),900)}
function startGame(){if(started)return;started=true;$('menu').classList.add('hidden');$('hud').classList.remove('hidden');toast('DUNGEON AWAKENED');renderer.domElement.requestPointerLock?.()}
function endGame(){started=false;document.exitPointerLock?.();$('gameover').classList.remove('hidden');$('resultText').textContent=`Level ${level} · Floor ${floor} · ${kills} defeated · ${gold} gold`}
function animate(){requestAnimationFrame(animate);let dt=Math.min(clock.getDelta(),.04);update(dt);renderer.render(scene,camera)}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}
addEventListener('resize',resize);addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(k==='w')input.z=-1;if(k==='s')input.z=1;if(k==='a')input.x=-1;if(k==='d')input.x=1;if(k==='q')skill('slash');if(k==='e')skill('burst');if(k==='r')skill('dash')});addEventListener('keyup',e=>{let k=e.key.toLowerCase();if(k==='w'||k==='s')input.z=0;if(k==='a'||k==='d')input.x=0});addEventListener('mousedown',()=>playerAttack());document.querySelectorAll('.skills button').forEach(b=>b.onclick=()=>skill(b.dataset.skill));$('start').onclick=startGame;$('restart').onclick=()=>location.reload();document.addEventListener('mousemove',e=>{if(started&&document.pointerLockElement===renderer.domElement)player.rotation.y-=e.movementX*.002});
function touchControls(){let box=document.createElement('div');box.id='touchUI';box.innerHTML='<div id="joy"><i></i></div><div class="touchSkills"><button data-s="slash">⚔</button><button data-s="burst">✦</button><button data-s="dash">➤</button></div>';document.body.appendChild(box);let j=$('joy'),knob=j.querySelector('i'),active=false,cx=0,cy=0;function move(x,y){let dx=x-cx,dy=y-cy,d=Math.hypot(dx,dy),m=34;if(d>m){dx=dx/d*m;dy=dy/d*m}knob.style.transform=`translate(${dx}px,${dy}px)`;input.x=dx/m;input.z=dy/m}function stop(){active=false;knob.style.transform='';input.x=input.z=0}j.onpointerdown=e=>{active=true;let r=j.getBoundingClientRect();cx=r.left+r.width/2;cy=r.top+r.height/2;j.setPointerCapture(e.pointerId);move(e.clientX,e.clientY)};j.onpointermove=e=>{if(active)move(e.clientX,e.clientY)};j.onpointerup=stop;j.onpointercancel=stop;box.querySelectorAll('button').forEach(b=>b.onpointerdown=e=>{e.preventDefault();skill(b.dataset.s)})}init();touchControls();setTimeout(()=>{$('boot').style.display='none';$('menu').classList.remove('hidden')},700);